### ISSUE TITLE
[Epic] Upgrade JWA 1.6 Commits to Redo

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#131]
Child of : https://github.com/StatCan/daaas/issues/1337
Initial table with all the commits visible in https://github.com/StatCan/daaas/issues/1242

## Issues to do and related commits
- [x] #143

| Original Title                                                        | Date     | Description                  | PR # | Note                             |
| --------------------------------------------------------------------- | -------- | ---------------------------- | ---- | -------------------------------- |
| StatCan/2-facilitate-local-development                                | 20/08/20 | StatCan/jupyter-apis@7ad65c2 | 6    |                                  |
| Merge pull request 9 from StatCan/fix-angular-component               | 20/08/21 | StatCan/jupyter-apis@f0b855d | 9    | Fix for bug	of existing pvcs     |
| Merge pull request 23 from StatCan/fix-dependabot-alerts              | 20/09/24 | StatCan/jupyter-apis@1a50add | 23   | AfterContentCheck                |
| Merge pull request 12 from StatCan/fix-kubeflow-collision-information | 20/08/21 | StatCan/jupyter-apis@5caa0a4 | 12   | css fix	X                        |
| Merge pull request #13 from StatCan/3-fix-front-end-file-permissions  | 20/08/21 | StatCan/jupyter-apis@978c814 | 13   | Chmod +x on files. Maybe needed? |

- [x] 1.3 ?

| Original Title                                      | Date     | Description                  | PR #               | Note           |
| --------------------------------------------------- | -------- | ---------------------------- | ------------------ | -------------- |
| feat(i18n): Add i18n functionality on top of KF 1.3 | 22/03/07 | StatCan/jupyter-apis@813f13a | N/A i18n for 1.3 ? | ?              |
| update spawner_ui_config                            | 22/03/11 | StatCan/jupyter-apis@866a7c8 | 116                | fix-image-icon | X

- [x] #134

| Original Title                                  | Date     | Description                  | PR # | Note                     |
| ----------------------------------------------- | -------- | ---------------------------- | ---- | ------------------------ |
| Merge pull request 48 from StatCan/feat-env-var | 21/01/21 | StatCan/jupyter-apis@2c1532b | 48   | Add env var for notebook |

- [x] #142

| Original Title                          | Date     | Description                  | PR # | Note                     |
| --------------------------------------- | -------- | ---------------------------- | ---- | ------------------------ |
| feat(imagePullPolicy): Change to Always | 22/05/04 | StatCan/jupyter-apis@2113334 | 120  | image pull policy change |            
| feat(imagePullPolicy): Add and set it   | 22/06/06 | StatCan/jupyter-apis@d105c5a | 121  | One weird change?        |            

- [x] #135

| Original Title         | Date     | Description                  | PR # | Note     |
| ---------------------- | -------- | ---------------------------- | ---- | -------- |
| StatCan/add-ui-for-sas | 22/07/12 | StatCan/jupyter-apis@5eef1a0 | 122  | Add sass |      
| Statcan/@cbrown/1335-non-employee-rbac |  14/09/2022 | https://github.com/StatCan/jupyter-apis/commit/1ca7a351e92efd22080282774b8cfa4dcaef14b4 | 129 | Collin changes        

- [x] #136

| Original Title                                                    | Date     | Description                  | PR # | Note                                                                   |
| ----------------------------------------------------------------- | -------- | ---------------------------- | ---- | ---------------------------------------------------------------------- |
| Merge pull request #60 from StatCan/image-selection-hint          | 21/04/20 | StatCan/jupyter-apis@5daefc3 | 60   | Add image text hint                                                    |            
| Merge pull request #30 from StatCan/Change-the-hint-image-message | 20/10/14 | StatCan/jupyter-apis@9d02488 | 30   | Change a message	SHouldnt need should be with i18n X (merge with i18n) |            

- [x] #137

| Original Title                                            | Date     | Description                  | PR # | Note                                            |
| --------------------------------------------------------- | -------- | ---------------------------- | ---- | ----------------------------------------------- |
| Merge pull request #38 from StatCan/fix-max-limits        | 20/11/03 | StatCan/jupyter-apis@344d4fc | 38   | fix: update ram limitsX - find where merge with |            
| Merge pull request #45 from StatCan/fix-gpu-specs         | 20/12/16 | StatCan/jupyter-apis@0e116fd | 45   | Validation GPU                                  |            
| Merge pull request #57 from StatCan/lower-gpu-cpu-request | 21/02/16 | StatCan/jupyter-apis@0b55d4d | 57   | lower-gpu-cpu-request                           |            
| feat: change cpu limit                                    | 22/04/11 | StatCan/jupyter-apis@bdf857c | 119  | change cpu limit                                |            

- [x] #138

| Original Title                                                         | Date     | Description                  | PR # | Note                                                                 |
| ---------------------------------------------------------------------- | -------- | ---------------------------- | ---- | -------------------------------------------------------------------- |
| Merge pull request #19 from StatCan/notebook-server-validation         | 20/09/16 | StatCan/jupyter-apis@22bdc13 | 19   | Name validation, CPu error, component error, default values	X - VERY |            
| Merge pull request #51 from StatCan/50-add-validation-mounted-pvc      | 21/01/07 | StatCan/jupyter-apis@8641aab | 51   | Validation Mounted volume	X                                          |            
| Merge pull request #61 from StatCan/59-add-custom-image-url-validation | 21/05/21 | StatCan/jupyter-apis@416bcb1 | 61   | custom-image-url-validation	X                                        |            

- [x] #139

| Original Title                                                    | Date     | Description                  | PR # | Note           |
| ----------------------------------------------------------------- | -------- | ---------------------------- | ---- | -------------- |
| Merge pull request #20 from StatCan/18-destroy-old-notebooks      | 20/10/06 | StatCan/jupyter-apis@2e9daf6 | 20   | VOLUME TABLE   |            
| Merge pull request #29 from StatCan/28-data-volume-ui-is-squashed | 20/10/07 | StatCan/jupyter-apis@738e6fd | 29   | fix CSS VoLUME |            

- [x] #140

| Original Title                                           | Date     | Description                  | PR #        | Note                   |
| -------------------------------------------------------- | -------- | ---------------------------- | ----------- | ---------------------- |
| Merge pull request #27 from StatCan/kubecost-estimates   | 20/10/21 | StatCan/jupyter-apis@49dea69 | 27	Kubecost |                        |            
| Merge pull request #34 from StatCan/fix-kubecost-error   | 20/11/06 | StatCan/jupyter-apis@d412a39 | 34	fix      | kubecost               |            
| Merge pull request #40 from StatCan/fix-kubecost-message | 20/11/10 | StatCan/jupyter-apis@0fba437 | 40          | fix kubecost message - |        
| feat: bring back cubecost table | 22/08/118 | StatCan/jupyter-apis@9835ca1 | 124 |         

- [x] #141

| Original Title            | Date     | Description                  | PR # | Note              |
| ------------------------- | -------- | ---------------------------- | ---- | ----------------- |
| fix(prob volumes)         | 21/09/22 | StatCan/jupyter-apis@da808ea | 63   | prob Volume       |            
| fix(use the better label) | 21/09/22 | StatCan/jupyter-apis@e0a6302 | 64   | add-prob-volv2    |            
| add prob volume label     | 21/09/29 | StatCan/jupyter-apis@24e2ce1 | 66   | prob-volume-label |    

- [ ] Fix Table look with css (This is a possible item to check once all the other work is complet)

## Additional fixes

- [x] https://github.com/StatCan/jupyter-apis/issues/156
- [x] https://github.com/StatCan/jupyter-apis/issues/157
- [x] https://github.com/StatCan/jupyter-apis/issues/158

**Comment by mathis-marcotte** [comment]
The frontend looks a bit updated, so we will try it out and see what people think. If there is negative feedback, we can revert those differences without breaking the whole 1.6 upgrade of jupyter-apis
