### ISSUE TITLE
Deploy Angular i18n

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#133]
This is the logical next step of the investigation made in https://github.com/StatCan/jupyter-apis/issues/126

## TODOs
Those were included in the original ticket but since not all of them got to fr
- [x] Take standalone example from repo and integrated it with jupyter-apis repo. Specifically, make k8s folder, taskfile, k3d config, etc. so that we can build jupyter-apis `Dockerfile` and test locally https://github.com/wg102/k3d-example.

- [x] Update jupyter-apis Dockerfile to include front-end build logic that aligns with KF 1.6 (i.e. `ng build --localize=...`). Specifically, we need to update the following lines: https://github.com/StatCan/jupyter-apis/blob/main/Dockerfile#L2-L17
- [x] Update jupyter-apis Dockerfile base image to be alpine instead of scratch. Reason is that we need to be able to use `cp` in init container to move static files into stock NGINX container. https://github.com/StatCan/jupyter-apis/blob/main/Dockerfile#L30
- [x] Remove static file serving logic from golang application (https://github.com/StatCan/jupyter-apis/blob/main/main.go#L250-L263) - reason is that NGINX static file server will handle this concern.
- [ ] Update the jupyter-apis deployment (https://github.com/StatCan/aaw-kubeflow-manifests/blob/aaw-dev-cc-00/kustomize/apps/jupyter-web-app/base/deployment.yaml) to reflect the deployment strategy used in https://github.com/StatCan/aws-js-s3-explorer/blob/main/k8s/s3proxy-deploy.yaml. Specifically:
    - [x] Need to add a stock NGINX container that will serve the application built in the `dist` folder.
    - [x] Need to add an init container based off of the refactored jupyter-apis Docker image - the purpose of this is to do a recursive copy of the `dist` static files onto the `/etc/nginx/html` location of the nginx container (this is the default place that nginx serves static files from).
    - [x] Need to add empty volume that gets mounted to both init container and nginx container.
    - [ ] Need to do one of the following:
        - [ ] Update the jupyter-apis *service* so that it forwards traffic to port 80 (or whatever port NGINX listens on by default) on pods behind that service; or
        - [ ] Update the NGINX container to serve on port 5000 so that the existing `jupyter-web-app-service` will continue to forward to the correct port.
    - [ ] Apply nginx configuration to the deployment as a configmap that gets mounted to the nginx container as a volume to `/etc/nginx/nginx.conf`

- [ ] Change anything that references `/en` or `/fr` to `/jupyter/en` and `/jupyter/fr` because in central dashboard we will access this via /jupyter prefix.

# Testing TODO
- [ ] Can we successfully run the 2-container pod (NGINX and golang API) locally (i.e. all AJAX calls from browser are successful, i18n routing works correctly).

# Steps:

1. Get k3d deployment working with manual port-forward on pod.
2. Modify service so that we are forwarding to the right port (the one ngx in listening on by default, prob 8080)
3. Refactor aaw kubeflow manifest deployment, to reflect our local k8s manifest folder
4. Testing against dev.

**Comment by wg102** [comment]
The current work can be seen in branch https://github.com/StatCan/jupyter-apis/tree/fix-i18n-angular

There is currently an issue that the i18n files needed suche as messages.xlf are not in the right location.

**Comment by wg102** [comment]
The image with the jwa + backend seems to finally build. Now it will be to test it locally to try and see if I can use port-forward on local

**Comment by wg102** [comment]
We will need to add code to force the `en-US` to `en` and such

**Comment by wg102** [comment]
The Pr for the manifest is ready.

**Comment by wg102** [comment]
(Adding Collin to reflect his work on this)
